### ISSUE TITLE
Support reference to schema by file path

### ISSUE THREAD

**Issue by bryancross** [postman-solutions-eng/postman-contract-test-generator#4]
Support identifying the schema to be tested by file path, eg:

`./postman/schemas/myapi.yaml`

It's a best practice in CI and GitOps to reference assets that exist in the repository.  This capability would ease integration of the generator in CI pipelines.  Because the tests are tied to a specific asset in a specific commit it will also be auditable.

**Comment by jordanwalsh23** [comment]
I've added the ability to reference a schema by URL in PR #6. I'll take a look at using a file path as wll.

**Comment by jordanwalsh23** [comment]
I actually found a way that you can do this as follows:

```yaml
name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Read README.md
         id: schema
         uses: jaywcjlove/github-action-read-file@main
         with:
             branch: development
             path: <path-to-schema.yaml>
      - name: Install Postman CLI
         uses: actions/checkout@v4
         run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
         run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
         run: |
          postman collection run "<collection-id> --env-var "env-schema=${{ steps.schema.outputs.content }}" --env-var "env-server=<server URL>"
```

I don't see a way of doing in the scripts themselves, so using actions to do the work for us works well.
